project_id = "uasyjxnaqaeiixtvuniq"

[functions.create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-teacher-payment]
verify_jwt = true

[functions.send-marketing-email]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-sms-verification]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = true

[functions.export-documents]
verify_jwt = true

[functions.send-document-reminder]
verify_jwt = false

[functions.send-promo-notification]
verify_jwt = true
